/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDividendosRouteImport } from './routes/_authenticated/dividendos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as ApiPublicRefreshProventosRouteImport } from './routes/api/public/refresh-proventos'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDividendosRoute = AuthenticatedDividendosRouteImport.update({
  id: '/_authenticated/dividendos',
  path: '/dividendos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/_authenticated/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRefreshProventosRoute =
  ApiPublicRefreshProventosRouteImport.update({
    id: '/api/public/refresh-proventos',
    path: '/api/public/refresh-proventos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dividendos': typeof AuthenticatedDividendosRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/refresh-proventos': typeof ApiPublicRefreshProventosRoute
}
export interface FileRoutesByTo {
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dividendos': typeof AuthenticatedDividendosRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/refresh-proventos': typeof ApiPublicRefreshProventosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dividendos': typeof AuthenticatedDividendosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/refresh-proventos': typeof ApiPublicRefreshProventosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/configuracoes'
    | '/dividendos'
    | '/'
    | '/api/public/refresh-proventos'
  fileRoutesByTo: FileRoutesByTo
  to: '/configuracoes' | '/dividendos' | '/' | '/api/public/refresh-proventos'
  id:
    | '__root__'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dividendos'
    | '/_authenticated/'
    | '/api/public/refresh-proventos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDividendosRoute: typeof AuthenticatedDividendosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  ApiPublicRefreshProventosRoute: typeof ApiPublicRefreshProventosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dividendos': {
      id: '/_authenticated/dividendos'
      path: '/dividendos'
      fullPath: '/dividendos'
      preLoaderRoute: typeof AuthenticatedDividendosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-proventos': {
      id: '/api/public/refresh-proventos'
      path: '/api/public/refresh-proventos'
      fullPath: '/api/public/refresh-proventos'
      preLoaderRoute: typeof ApiPublicRefreshProventosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDividendosRoute: AuthenticatedDividendosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  ApiPublicRefreshProventosRoute: ApiPublicRefreshProventosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
