/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DividendosRouteImport } from './routes/dividendos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRefreshProventosRouteImport } from './routes/api/public/refresh-proventos'

const DividendosRoute = DividendosRouteImport.update({
  id: '/dividendos',
  path: '/dividendos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshProventosRoute =
  ApiPublicRefreshProventosRouteImport.update({
    id: '/api/public/refresh-proventos',
    path: '/api/public/refresh-proventos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dividendos': typeof DividendosRoute
  '/api/public/refresh-proventos': typeof ApiPublicRefreshProventosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dividendos': typeof DividendosRoute
  '/api/public/refresh-proventos': typeof ApiPublicRefreshProventosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dividendos': typeof DividendosRoute
  '/api/public/refresh-proventos': typeof ApiPublicRefreshProventosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/dividendos'
    | '/api/public/refresh-proventos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configuracoes' | '/dividendos' | '/api/public/refresh-proventos'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/dividendos'
    | '/api/public/refresh-proventos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DividendosRoute: typeof DividendosRoute
  ApiPublicRefreshProventosRoute: typeof ApiPublicRefreshProventosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dividendos': {
      id: '/dividendos'
      path: '/dividendos'
      fullPath: '/dividendos'
      preLoaderRoute: typeof DividendosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-proventos': {
      id: '/api/public/refresh-proventos'
      path: '/api/public/refresh-proventos'
      fullPath: '/api/public/refresh-proventos'
      preLoaderRoute: typeof ApiPublicRefreshProventosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DividendosRoute: DividendosRoute,
  ApiPublicRefreshProventosRoute: ApiPublicRefreshProventosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
