/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDividendosRouteImport } from './routes/_authenticated/dividendos'
import { Route as AuthenticatedSimuladorRouteImport } from './routes/_authenticated/simulador'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as ApiPublicRefreshProventosRouteImport } from './routes/api/public/refresh-proventos'
import { Route as ApiPublicAuthSessionRouteImport } from './routes/api/public/auth/session'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDividendosRoute = AuthenticatedDividendosRouteImport.update({
  id: '/dividendos',
  path: '/dividendos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimuladorRoute = AuthenticatedSimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRefreshProventosRoute =
  ApiPublicRefreshProventosRouteImport.update({
    id: '/api/public/refresh-proventos',
    path: '/api/public/refresh-proventos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthSessionRoute = ApiPublicAuthSessionRouteImport.update({
  id: '/api/public/auth/session',
  path: '/api/public/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dividendos': typeof AuthenticatedDividendosRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/refresh-proventos': typeof ApiPublicRefreshProventosRoute
  '/api/public/auth/session': typeof ApiPublicAuthSessionRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dividendos': typeof AuthenticatedDividendosRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/refresh-proventos': typeof ApiPublicRefreshProventosRoute
  '/api/public/auth/session': typeof ApiPublicAuthSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dividendos': typeof AuthenticatedDividendosRoute
  '/_authenticated/simulador': typeof AuthenticatedSimuladorRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/refresh-proventos': typeof ApiPublicRefreshProventosRoute
  '/api/public/auth/session': typeof ApiPublicAuthSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carteira'
    | '/configuracoes'
    | '/dividendos'
    | '/simulador'
    | '/usuarios'
    | '/api/public/refresh-proventos'
    | '/api/public/auth/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/carteira'
    | '/configuracoes'
    | '/dividendos'
    | '/simulador'
    | '/usuarios'
    | '/'
    | '/api/public/refresh-proventos'
    | '/api/public/auth/session'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/carteira'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dividendos'
    | '/_authenticated/simulador'
    | '/_authenticated/usuarios'
    | '/_authenticated/'
    | '/api/public/refresh-proventos'
    | '/api/public/auth/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicRefreshProventosRoute: typeof ApiPublicRefreshProventosRoute
  ApiPublicAuthSessionRoute: typeof ApiPublicAuthSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dividendos': {
      id: '/_authenticated/dividendos'
      path: '/dividendos'
      fullPath: '/dividendos'
      preLoaderRoute: typeof AuthenticatedDividendosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulador': {
      id: '/_authenticated/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof AuthenticatedSimuladorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/refresh-proventos': {
      id: '/api/public/refresh-proventos'
      path: '/api/public/refresh-proventos'
      fullPath: '/api/public/refresh-proventos'
      preLoaderRoute: typeof ApiPublicRefreshProventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/session': {
      id: '/api/public/auth/session'
      path: '/api/public/auth/session'
      fullPath: '/api/public/auth/session'
      preLoaderRoute: typeof ApiPublicAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDividendosRoute: typeof AuthenticatedDividendosRoute
  AuthenticatedSimuladorRoute: typeof AuthenticatedSimuladorRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDividendosRoute: AuthenticatedDividendosRoute,
  AuthenticatedSimuladorRoute: AuthenticatedSimuladorRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicRefreshProventosRoute: ApiPublicRefreshProventosRoute,
  ApiPublicAuthSessionRoute: ApiPublicAuthSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
